// src/lib/grammar-reference-data.ts
// Grammar Reference: Parts of Speech + Essential Grammar Topics (Hindi + English)

export interface PosType {
  name: string;
  nameHindi: string;
  description: string;
  descriptionHindi: string;
  examples: string;
}

export interface GrammarPosTopic {
  id: string;
  name: string;
  nameHindi: string;
  emoji: string;
  definition: string;
  definitionHindi: string;
  color: string;        // Tailwind bg class for card
  borderColor: string;  // Tailwind border class
  textColor: string;    // Tailwind text class
  types: PosType[];
}

export const GRAMMAR_REFERENCE_DATA: GrammarPosTopic[] = [
  {
    id: "noun",
    name: "Noun",
    nameHindi: "संज्ञा",
    emoji: "📦",
    definition: "A noun is a word that names a person, place, thing, or idea.",
    definitionHindi: "संज्ञा वह शब्द है जो किसी व्यक्ति, स्थान, वस्तु या भाव का नाम बताता है।",
    color: "bg-blue-500 dark:bg-blue-600",
    borderColor: "border-blue-500",
    textColor: "text-blue-700 dark:text-blue-300",
    types: [
      {
        name: "Proper Noun",
        nameHindi: "व्यक्तिवाचक संज्ञा",
        description: "Names a specific person, place, or thing. Always capitalized.",
        descriptionHindi: "किसी विशेष व्यक्ति, स्थान या वस्तु का नाम।",
        examples: "India, Ram, Taj Mahal, Monday",
      },
      {
        name: "Common Noun",
        nameHindi: "जातिवाचक संज्ञा",
        description: "Names a general person, place, or thing.",
        descriptionHindi: "किसी जाति या वर्ग का सामान्य नाम।",
        examples: "boy, city, dog, book, teacher",
      },
      {
        name: "Collective Noun",
        nameHindi: "समूहवाचक संज्ञा",
        description: "Names a group or collection of people/things.",
        descriptionHindi: "व्यक्तियों या वस्तुओं के समूह का नाम।",
        examples: "team, family, flock, army, class",
      },
      {
        name: "Material Noun",
        nameHindi: "द्रव्यवाचक संज्ञा",
        description: "Names a material or substance that things are made of.",
        descriptionHindi: "उस पदार्थ का नाम जिससे चीज़ें बनती हैं।",
        examples: "gold, iron, water, wood, rice",
      },
      {
        name: "Abstract Noun",
        nameHindi: "भाववाचक संज्ञा",
        description: "Names an idea, feeling, quality, or state that cannot be touched.",
        descriptionHindi: "जिसे छू नहीं सकते — भाव, गुण, या अवस्था का नाम।",
        examples: "love, happiness, courage, freedom, childhood",
      },
    ],
  },
  {
    id: "pronoun",
    name: "Pronoun",
    nameHindi: "सर्वनाम",
    emoji: "👤",
    definition: "A pronoun is a word used in place of a noun to avoid repetition.",
    definitionHindi: "सर्वनाम वह शब्द है जो संज्ञा के स्थान पर प्रयोग होता है।",
    color: "bg-purple-500 dark:bg-purple-600",
    borderColor: "border-purple-500",
    textColor: "text-purple-700 dark:text-purple-300",
    types: [
      {
        name: "Personal Pronoun",
        nameHindi: "पुरुषवाचक सर्वनाम",
        description: "Refers to specific people or things.",
        descriptionHindi: "किसी विशेष व्यक्ति या वस्तु की ओर संकेत करता है।",
        examples: "I, you, he, she, it, we, they",
      },
      {
        name: "Possessive Pronoun",
        nameHindi: "अधिकारवाचक सर्वनाम",
        description: "Shows ownership or possession.",
        descriptionHindi: "अधिकार या स्वामित्व बताता है।",
        examples: "mine, yours, his, hers, ours, theirs",
      },
      {
        name: "Reflexive Pronoun",
        nameHindi: "निजवाचक सर्वनाम",
        description: "Refers back to the subject of the sentence.",
        descriptionHindi: "जब कर्ता खुद पर क्रिया करता है।",
        examples: "myself, yourself, himself, herself, ourselves",
      },
      {
        name: "Demonstrative Pronoun",
        nameHindi: "संकेतवाचक सर्वनाम",
        description: "Points to a specific person or thing.",
        descriptionHindi: "किसी विशेष व्यक्ति या वस्तु की ओर इशारा करता है।",
        examples: "this, that, these, those",
      },
      {
        name: "Interrogative Pronoun",
        nameHindi: "प्रश्नवाचक सर्वनाम",
        description: "Used to ask questions.",
        descriptionHindi: "प्रश्न पूछने के लिए प्रयोग होता है।",
        examples: "who, whom, whose, which, what",
      },
      {
        name: "Relative Pronoun",
        nameHindi: "संबंधवाचक सर्वनाम",
        description: "Connects a clause to a noun it refers to.",
        descriptionHindi: "दो वाक्यों को जोड़ता है और संज्ञा से संबंध बताता है।",
        examples: "who, whom, whose, which, that",
      },
      {
        name: "Indefinite Pronoun",
        nameHindi: "अनिश्चयवाचक सर्वनाम",
        description: "Refers to non-specific people or things.",
        descriptionHindi: "किसी अनिश्चित व्यक्ति या वस्तु के लिए।",
        examples: "someone, anyone, everyone, nobody, each",
      },
    ],
  },
  {
    id: "verb",
    name: "Verb",
    nameHindi: "क्रिया",
    emoji: "⚡",
    definition: "A verb is a word that shows an action, state, or occurrence.",
    definitionHindi: "क्रिया वह शब्द है जो किसी काम का होना या करना बताता है।",
    color: "bg-red-500 dark:bg-red-600",
    borderColor: "border-red-500",
    textColor: "text-red-700 dark:text-red-300",
    types: [
      {
        name: "Transitive Verb",
        nameHindi: "सकर्मक क्रिया",
        description: "Needs an object to complete the meaning. (What? / Whom?)",
        descriptionHindi: "जिसे पूरा अर्थ देने के लिए कर्म (object) चाहिए।",
        examples: "eat (an apple), read (a book), play (cricket)",
      },
      {
        name: "Intransitive Verb",
        nameHindi: "अकर्मक क्रिया",
        description: "Does NOT need an object. The action is complete by itself.",
        descriptionHindi: "जिसे कर्म की ज़रूरत नहीं — क्रिया अपने आप पूरी है।",
        examples: "sleep, run, laugh, cry, go, sit",
      },
      {
        name: "Auxiliary (Helping) Verb",
        nameHindi: "सहायक क्रिया",
        description: "Helps the main verb to form tenses, questions, or negatives.",
        descriptionHindi: "मुख्य क्रिया की मदद करती है — Tense, प्रश्न या नकारात्मक बनाने में।",
        examples: "is, am, are, was, were, has, have, had, do, does, did",
      },
      {
        name: "Modal Verb",
        nameHindi: "विधि सूचक क्रिया",
        description: "Shows ability, possibility, permission, or obligation.",
        descriptionHindi: "योग्यता, संभावना, अनुमति या बाध्यता बताती है।",
        examples: "can, could, may, might, shall, should, will, would, must",
      },
    ],
  },
  {
    id: "adjective",
    name: "Adjective",
    nameHindi: "विशेषण",
    emoji: "🎨",
    definition: "An adjective is a word that describes or modifies a noun or pronoun.",
    definitionHindi: "विशेषण वह शब्द है जो संज्ञा या सर्वनाम की विशेषता बताता है।",
    color: "bg-emerald-500 dark:bg-emerald-600",
    borderColor: "border-emerald-500",
    textColor: "text-emerald-700 dark:text-emerald-300",
    types: [
      {
        name: "Adjective of Quality",
        nameHindi: "गुणवाचक विशेषण",
        description: "Describes the quality or kind of a noun. (How is it?)",
        descriptionHindi: "संज्ञा का गुण, दोष या स्वभाव बताता है।",
        examples: "good, beautiful, tall, brave, kind, lazy",
      },
      {
        name: "Adjective of Quantity",
        nameHindi: "परिमाणवाचक विशेषण",
        description: "Shows how much of a thing. (How much?)",
        descriptionHindi: "कितनी मात्रा है, यह बताता है।",
        examples: "some, much, little, enough, whole, half",
      },
      {
        name: "Adjective of Number",
        nameHindi: "संख्यावाचक विशेषण",
        description: "Shows how many or in what order. (How many?)",
        descriptionHindi: "कितने या किस क्रम में — यह बताता है।",
        examples: "one, two, first, second, few, many, several",
      },
      {
        name: "Demonstrative Adjective",
        nameHindi: "संकेतवाचक विशेषण",
        description: "Points out which noun is meant.",
        descriptionHindi: "किस संज्ञा की बात हो रही है — यह इशारा करता है।",
        examples: "this book, that pen, these boys, those girls",
      },
      {
        name: "Interrogative Adjective",
        nameHindi: "प्रश्नवाचक विशेषण",
        description: "Used with a noun to ask a question.",
        descriptionHindi: "संज्ञा के साथ प्रश्न पूछने के लिए।",
        examples: "which book?, what color?, whose pen?",
      },
    ],
  },
  {
    id: "adverb",
    name: "Adverb",
    nameHindi: "क्रिया विशेषण",
    emoji: "🏃",
    definition: "An adverb modifies a verb, adjective, or another adverb. It tells how, when, where, or how much.",
    definitionHindi: "क्रिया विशेषण क्रिया, विशेषण या अन्य क्रिया विशेषण की विशेषता बताता है।",
    color: "bg-amber-500 dark:bg-amber-600",
    borderColor: "border-amber-500",
    textColor: "text-amber-700 dark:text-amber-300",
    types: [
      {
        name: "Adverb of Time",
        nameHindi: "कालवाचक क्रिया विशेषण",
        description: "Tells WHEN an action happens.",
        descriptionHindi: "क्रिया कब होती है — यह बताता है।",
        examples: "now, today, yesterday, soon, already, yet",
      },
      {
        name: "Adverb of Place",
        nameHindi: "स्थानवाचक क्रिया विशेषण",
        description: "Tells WHERE an action happens.",
        descriptionHindi: "क्रिया कहाँ होती है — यह बताता है।",
        examples: "here, there, everywhere, inside, outside, above",
      },
      {
        name: "Adverb of Manner",
        nameHindi: "रीतिवाचक क्रिया विशेषण",
        description: "Tells HOW an action is done.",
        descriptionHindi: "क्रिया कैसे होती है — यह बताता है।",
        examples: "slowly, quickly, carefully, loudly, happily",
      },
      {
        name: "Adverb of Frequency",
        nameHindi: "आवृत्तिवाचक क्रिया विशेषण",
        description: "Tells HOW OFTEN an action happens.",
        descriptionHindi: "क्रिया कितनी बार होती है — यह बताता है।",
        examples: "always, never, often, sometimes, usually, rarely",
      },
      {
        name: "Adverb of Degree",
        nameHindi: "परिमाणवाचक क्रिया विशेषण",
        description: "Tells HOW MUCH or to what extent.",
        descriptionHindi: "कितना या किस हद तक — यह बताता है।",
        examples: "very, too, quite, almost, enough, extremely",
      },
    ],
  },
  {
    id: "preposition",
    name: "Preposition",
    nameHindi: "पूर्वसर्ग",
    emoji: "📍",
    definition: "A preposition shows the relationship of a noun/pronoun to another word in the sentence.",
    definitionHindi: "पूर्वसर्ग संज्ञा/सर्वनाम का वाक्य के अन्य शब्दों से संबंध बताता है।",
    color: "bg-rose-500 dark:bg-rose-600",
    borderColor: "border-rose-500",
    textColor: "text-rose-700 dark:text-rose-300",
    types: [
      {
        name: "Preposition of Time",
        nameHindi: "समय का पूर्वसर्ग",
        description: "Shows WHEN something happens.",
        descriptionHindi: "समय बताता है — कब?",
        examples: "at 5 PM, on Monday, in March, during summer, since 2020",
      },
      {
        name: "Preposition of Place",
        nameHindi: "स्थान का पूर्वसर्ग",
        description: "Shows WHERE something is located.",
        descriptionHindi: "स्थान बताता है — कहाँ?",
        examples: "at school, on the table, in the box, under the bed",
      },
      {
        name: "Preposition of Direction",
        nameHindi: "दिशा का पूर्वसर्ग",
        description: "Shows movement towards a direction.",
        descriptionHindi: "दिशा या गति बताता है — किधर?",
        examples: "to the park, into the room, through the tunnel, across the river",
      },
      {
        name: "Preposition of Agent/Instrument",
        nameHindi: "कर्ता/साधन का पूर्वसर्ग",
        description: "Shows by whom or with what an action is done.",
        descriptionHindi: "किसके द्वारा या किससे — यह बताता है।",
        examples: "by the teacher, with a pen, by hand",
      },
    ],
  },
  {
    id: "conjunction",
    name: "Conjunction",
    nameHindi: "समुच्चयबोधक",
    emoji: "🔗",
    definition: "A conjunction joins words, phrases, or clauses together.",
    definitionHindi: "समुच्चयबोधक दो शब्दों, वाक्यांशों या वाक्यों को जोड़ता है।",
    color: "bg-teal-500 dark:bg-teal-600",
    borderColor: "border-teal-500",
    textColor: "text-teal-700 dark:text-teal-300",
    types: [
      {
        name: "Coordinating Conjunction",
        nameHindi: "समानाधिकरण समुच्चयबोधक",
        description: "Joins equal parts (word + word, clause + clause). Remember: FANBOYS.",
        descriptionHindi: "दो समान भागों को जोड़ता है। याद रखें: FANBOYS",
        examples: "for, and, nor, but, or, yet, so (FANBOYS)",
      },
      {
        name: "Subordinating Conjunction",
        nameHindi: "व्यधिकरण समुच्चयबोधक",
        description: "Joins a dependent clause to an independent clause.",
        descriptionHindi: "एक आश्रित उपवाक्य को मुख्य वाक्य से जोड़ता है।",
        examples: "because, although, if, when, while, since, until, after",
      },
      {
        name: "Correlative Conjunction",
        nameHindi: "सहसंबंधी समुच्चयबोधक",
        description: "Work in pairs to join equal parts.",
        descriptionHindi: "जोड़े में काम करते हैं।",
        examples: "either...or, neither...nor, both...and, not only...but also",
      },
    ],
  },
  {
    id: "interjection",
    name: "Interjection",
    nameHindi: "विस्मयादिबोधक",
    emoji: "😲",
    definition: "An interjection is a word that expresses a sudden feeling or emotion.",
    definitionHindi: "विस्मयादिबोधक वह शब्द है जो अचानक भावना या संवेग को व्यक्त करता है।",
    color: "bg-pink-500 dark:bg-pink-600",
    borderColor: "border-pink-500",
    textColor: "text-pink-700 dark:text-pink-300",
    types: [
      {
        name: "Joy / खुशी",
        nameHindi: "खुशी का विस्मयादिबोधक",
        description: "Expresses happiness or excitement.",
        descriptionHindi: "खुशी या उत्साह व्यक्त करता है।",
        examples: "Hurray! Wow! Yippee! Bravo!",
      },
      {
        name: "Sorrow / दुख",
        nameHindi: "दुख का विस्मयादिबोधक",
        description: "Expresses sadness or grief.",
        descriptionHindi: "दुख या शोक व्यक्त करता है।",
        examples: "Alas! Oh no! Ouch!",
      },
      {
        name: "Surprise / आश्चर्य",
        nameHindi: "आश्चर्य का विस्मयादिबोधक",
        description: "Expresses surprise or wonder.",
        descriptionHindi: "आश्चर्य या अचंभा व्यक्त करता है।",
        examples: "Oh! What! Really! Gosh!",
      },
      {
        name: "Greeting / अभिवादन",
        nameHindi: "अभिवादन का विस्मयादिबोधक",
        description: "Used for greeting or calling attention.",
        descriptionHindi: "अभिवादन या ध्यान आकर्षित करने के लिए।",
        examples: "Hello! Hi! Hey! Welcome!",
      },
    ],
  },

  // ─── ADDITIONAL GRAMMAR TOPICS ────────────────────────────────

  {
    id: "article",
    name: "Article",
    nameHindi: "उपपद / आर्टिकल",
    emoji: "📰",
    definition: "An article is a word used before a noun to show whether it is specific or general.",
    definitionHindi: "Article वह शब्द है जो संज्ञा से पहले लगता है — यह बताता है कि बात किसी खास या सामान्य चीज़ की हो रही है।",
    color: "bg-cyan-500 dark:bg-cyan-600",
    borderColor: "border-cyan-500",
    textColor: "text-cyan-700 dark:text-cyan-300",
    types: [
      {
        name: "Indefinite Article — A",
        nameHindi: "अनिश्चित उपपद — A",
        description: "Used before singular countable nouns starting with a consonant sound.",
        descriptionHindi: "व्यंजन ध्वनि से शुरू होने वाली एकवचन गणनीय संज्ञा से पहले।",
        examples: "a boy, a cat, a university (यू sound), a one-rupee coin",
      },
      {
        name: "Indefinite Article — An",
        nameHindi: "अनिश्चित उपपद — An",
        description: "Used before singular countable nouns starting with a vowel sound.",
        descriptionHindi: "स्वर ध्वनि से शुरू होने वाली एकवचन गणनीय संज्ञा से पहले।",
        examples: "an apple, an egg, an hour (silent h), an honest man",
      },
      {
        name: "Definite Article — The",
        nameHindi: "निश्चित उपपद — The",
        description: "Used when talking about a specific or already-known noun.",
        descriptionHindi: "जब किसी खास या पहले से ज्ञात संज्ञा की बात हो।",
        examples: "the sun, the Ganga, the book I gave you, the tallest boy",
      },
      {
        name: "Zero Article (No Article)",
        nameHindi: "शून्य उपपद (कोई Article नहीं)",
        description: "Some nouns don't need an article — uncountable nouns, plural general nouns, proper nouns.",
        descriptionHindi: "कुछ संज्ञाओं के पहले Article नहीं लगता — अगणनीय, बहुवचन सामान्य, व्यक्तिवाचक।",
        examples: "Water is life. Dogs are loyal. India is great. I like music.",
      },
    ],
  },
  {
    id: "tense",
    name: "Tense",
    nameHindi: "काल",
    emoji: "⏰",
    definition: "Tense shows the time of an action — when it happens: past, present, or future.",
    definitionHindi: "काल बताता है कि क्रिया कब होती है — भूतकाल, वर्तमान काल, या भविष्य काल।",
    color: "bg-indigo-500 dark:bg-indigo-600",
    borderColor: "border-indigo-500",
    textColor: "text-indigo-700 dark:text-indigo-300",
    types: [
      {
        name: "Simple Present",
        nameHindi: "सामान्य वर्तमान काल",
        description: "Habitual actions, facts, routines. [S + V1/V1s]",
        descriptionHindi: "आदत, सत्य, नियमित काम। [S + V1/V1s]",
        examples: "He plays cricket. The sun rises in the east.",
      },
      {
        name: "Present Continuous",
        nameHindi: "अपूर्ण वर्तमान काल",
        description: "Action happening right now. [S + is/am/are + V-ing]",
        descriptionHindi: "अभी हो रहा है। [S + is/am/are + V-ing]",
        examples: "She is reading a book. They are playing.",
      },
      {
        name: "Present Perfect",
        nameHindi: "पूर्ण वर्तमान काल",
        description: "Action just completed, result visible now. [S + has/have + V3]",
        descriptionHindi: "काम अभी पूरा हुआ है। [S + has/have + V3]",
        examples: "I have finished my homework. She has eaten lunch.",
      },
      {
        name: "Present Perfect Continuous",
        nameHindi: "पूर्ण अपूर्ण वर्तमान काल",
        description: "Action started in past and still continuing. [S + has/have been + V-ing]",
        descriptionHindi: "काम पहले शुरू हुआ और अभी तक जारी है।",
        examples: "He has been studying since morning. It has been raining for two hours.",
      },
      {
        name: "Simple Past",
        nameHindi: "सामान्य भूतकाल",
        description: "Action completed in the past. [S + V2]",
        descriptionHindi: "बीते समय में पूरा हो चुका काम। [S + V2]",
        examples: "She went to school. I ate an apple.",
      },
      {
        name: "Past Continuous",
        nameHindi: "अपूर्ण भूतकाल",
        description: "Action was ongoing at a specific past time. [S + was/were + V-ing]",
        descriptionHindi: "बीते समय में काम जारी था। [S + was/were + V-ing]",
        examples: "He was sleeping when I called. They were playing at 5 PM.",
      },
      {
        name: "Past Perfect",
        nameHindi: "पूर्ण भूतकाल",
        description: "Action completed before another past action. [S + had + V3]",
        descriptionHindi: "एक काम दूसरे भूतकाल के काम से पहले पूरा हो चुका था।",
        examples: "She had left before I arrived. I had eaten before he came.",
      },
      {
        name: "Past Perfect Continuous",
        nameHindi: "पूर्ण अपूर्ण भूतकाल",
        description: "Action had been ongoing before another past event. [S + had been + V-ing]",
        descriptionHindi: "काम भूतकाल में लंबे समय से जारी था किसी दूसरी घटना से पहले।",
        examples: "I had been waiting for an hour when the bus came.",
      },
      {
        name: "Simple Future",
        nameHindi: "सामान्य भविष्य काल",
        description: "Action that will happen in the future. [S + will/shall + V1]",
        descriptionHindi: "आने वाले समय में होने वाला काम। [S + will/shall + V1]",
        examples: "I will go to Delhi. She will help you.",
      },
      {
        name: "Future Continuous",
        nameHindi: "अपूर्ण भविष्य काल",
        description: "Action will be ongoing at a future time. [S + will be + V-ing]",
        descriptionHindi: "भविष्य में किसी समय काम जारी होगा।",
        examples: "I will be studying at 8 PM. They will be travelling tomorrow.",
      },
      {
        name: "Future Perfect",
        nameHindi: "पूर्ण भविष्य काल",
        description: "Action will be completed before a future time. [S + will have + V3]",
        descriptionHindi: "भविष्य में किसी समय से पहले काम पूरा हो चुका होगा।",
        examples: "She will have finished by 6 PM. I will have eaten before you come.",
      },
      {
        name: "Future Perfect Continuous",
        nameHindi: "पूर्ण अपूर्ण भविष्य काल",
        description: "Action will have been ongoing for a duration by a future point. [S + will have been + V-ing]",
        descriptionHindi: "भविष्य में किसी समय तक काम लंबे समय से जारी होगा।",
        examples: "By July, I will have been living here for 5 years.",
      },
    ],
  },
  {
    id: "voice",
    name: "Voice",
    nameHindi: "वाच्य",
    emoji: "🔄",
    definition: "Voice shows whether the subject performs the action (Active) or receives the action (Passive).",
    definitionHindi: "वाच्य बताता है कि कर्ता काम करता है (कर्तृवाच्य) या काम कर्ता पर होता है (कर्मवाच्य)।",
    color: "bg-violet-500 dark:bg-violet-600",
    borderColor: "border-violet-500",
    textColor: "text-violet-700 dark:text-violet-300",
    types: [
      {
        name: "Active Voice",
        nameHindi: "कर्तृवाच्य",
        description: "Subject DOES the action. Focus is on the doer. [S + V + O]",
        descriptionHindi: "कर्ता खुद काम करता है। ध्यान करने वाले पर है।",
        examples: "Ram eats an apple. She writes a letter. The teacher taught us.",
      },
      {
        name: "Passive Voice",
        nameHindi: "कर्मवाच्य",
        description: "Subject RECEIVES the action. Focus is on the receiver. [O + be + V3 + by S]",
        descriptionHindi: "कर्ता पर काम होता है। ध्यान सहने वाले पर है।",
        examples: "An apple is eaten by Ram. A letter was written by her.",
      },
      {
        name: "Active → Passive Rules",
        nameHindi: "परिवर्तन के नियम",
        description: "Swap Subject & Object. Change verb to 'be + V3'. Add 'by' before doer. Match tense.",
        descriptionHindi: "कर्ता व कर्म बदलो। क्रिया 'be + V3' करो। 'by' लगाओ। काल मिलाओ।",
        examples: "He helps me → I am helped by him. She wrote a poem → A poem was written by her.",
      },
    ],
  },
  {
    id: "narration",
    name: "Narration (Speech)",
    nameHindi: "कथन / वाक्",
    emoji: "💬",
    definition: "Narration is the way we report what someone said — directly (exact words) or indirectly (in our own words).",
    definitionHindi: "कथन बताता है कि किसी ने क्या कहा — सीधे (उसी के शब्दों में) या अप्रत्यक्ष (अपने शब्दों में)।",
    color: "bg-orange-500 dark:bg-orange-600",
    borderColor: "border-orange-500",
    textColor: "text-orange-700 dark:text-orange-300",
    types: [
      {
        name: "Direct Speech",
        nameHindi: "प्रत्यक्ष कथन",
        description: "The exact words of the speaker are quoted using inverted commas \" \".",
        descriptionHindi: "बोलने वाले के वही शब्द — inverted commas (\" \") में लिखे जाते हैं।",
        examples: "Ram said, \"I am happy.\" She said, \"I will come tomorrow.\"",
      },
      {
        name: "Indirect Speech",
        nameHindi: "अप्रत्यक्ष कथन",
        description: "The speaker's words are reported without quotes, with tense & pronoun changes.",
        descriptionHindi: "बोलने वाले की बात अपने शब्दों में बताई जाती है — Tense और Pronoun बदलते हैं।",
        examples: "Ram said that he was happy. She said that she would come the next day.",
      },
      {
        name: "Reporting Verb Changes",
        nameHindi: "Reporting Verb के नियम",
        description: "said → told/informed. say → tell. asked (for questions). ordered/requested (for commands).",
        descriptionHindi: "said → told, say → tell, प्रश्न → asked, आदेश → ordered/requested.",
        examples: "\"Sit down\" → He ordered me to sit down. \"Where is it?\" → She asked where it was.",
      },
      {
        name: "Tense Change Rules",
        nameHindi: "काल परिवर्तन नियम",
        description: "Present → Past. Past → Past Perfect. Will → Would. Can → Could. May → Might.",
        descriptionHindi: "वर्तमान → भूत। भूत → पूर्ण भूत। will → would. can → could. may → might.",
        examples: "\"I am going\" → He said he was going. \"I will help\" → She said she would help.",
      },
    ],
  },
  {
    id: "sentence-types",
    name: "Sentence Types",
    nameHindi: "वाक्य के प्रकार",
    emoji: "📝",
    definition: "Sentences are classified by their purpose — to state, ask, command, or express emotion.",
    definitionHindi: "वाक्यों को उनके उद्देश्य के अनुसार बाँटा जाता है — बताना, पूछना, आदेश देना, या भावना व्यक्त करना।",
    color: "bg-lime-600 dark:bg-lime-600",
    borderColor: "border-lime-600",
    textColor: "text-lime-700 dark:text-lime-300",
    types: [
      {
        name: "Declarative (Statement)",
        nameHindi: "विधानवाचक वाक्य",
        description: "Makes a statement or gives information. Ends with a full stop (.).",
        descriptionHindi: "कोई बात बताता है या जानकारी देता है। पूर्ण विराम (.) लगता है।",
        examples: "The sky is blue. I like mangoes. She is a doctor.",
      },
      {
        name: "Interrogative (Question)",
        nameHindi: "प्रश्नवाचक वाक्य",
        description: "Asks a question. Ends with a question mark (?).",
        descriptionHindi: "प्रश्न पूछता है। प्रश्नचिह्न (?) लगता है।",
        examples: "What is your name? Are you coming? Where do you live?",
      },
      {
        name: "Imperative (Command/Request)",
        nameHindi: "आज्ञावाचक वाक्य",
        description: "Gives a command, order, request, or advice. Subject (You) is hidden.",
        descriptionHindi: "आदेश, अनुरोध, या सलाह देता है। कर्ता (You) छिपा होता है।",
        examples: "Sit down. Please help me. Don't run in the hall. Open your books.",
      },
      {
        name: "Exclamatory (Emotion)",
        nameHindi: "विस्मयवाचक वाक्य",
        description: "Expresses strong feeling or emotion. Ends with an exclamation mark (!).",
        descriptionHindi: "तीव्र भावना व्यक्त करता है। विस्मयचिह्न (!) लगता है।",
        examples: "What a beautiful day! How kind of you! Hurray, we won!",
      },
    ],
  },
  {
    id: "degree-of-comparison",
    name: "Degree of Comparison",
    nameHindi: "तुलना की अवस्थाएँ",
    emoji: "📊",
    definition: "Degrees of comparison show how adjectives and adverbs change when comparing things.",
    definitionHindi: "तुलना की अवस्थाएँ बताती हैं कि विशेषण/क्रिया विशेषण तुलना करते समय कैसे बदलते हैं।",
    color: "bg-sky-500 dark:bg-sky-600",
    borderColor: "border-sky-500",
    textColor: "text-sky-700 dark:text-sky-300",
    types: [
      {
        name: "Positive Degree",
        nameHindi: "मूलावस्था",
        description: "Describes a quality without comparison. No -er or -est. Just the base adjective.",
        descriptionHindi: "बिना तुलना के गुण बताता है। सामान्य रूप।",
        examples: "Ram is tall. This flower is beautiful. She runs fast.",
      },
      {
        name: "Comparative Degree",
        nameHindi: "उत्तरावस्था",
        description: "Compares TWO things. Add -er or use 'more'. Uses 'than'.",
        descriptionHindi: "दो चीज़ों की तुलना। -er लगाओ या 'more' लगाओ। 'than' का प्रयोग।",
        examples: "Ram is taller than Shyam. This is more beautiful than that.",
      },
      {
        name: "Superlative Degree",
        nameHindi: "उत्तमावस्था",
        description: "Compares THREE or more. Add -est or use 'most'. Uses 'the'.",
        descriptionHindi: "तीन या अधिक की तुलना। -est लगाओ या 'most' लगाओ। 'the' लगता है।",
        examples: "Ram is the tallest in the class. This is the most beautiful flower.",
      },
      {
        name: "Irregular Comparisons",
        nameHindi: "अनियमित तुलना",
        description: "Some adjectives change completely: good→better→best, bad→worse→worst.",
        descriptionHindi: "कुछ विशेषण पूरी तरह बदल जाते हैं।",
        examples: "good → better → best, bad → worse → worst, little → less → least, many → more → most",
      },
    ],
  },
  {
    id: "gerund",
    name: "Gerund",
    nameHindi: "क्रियावाचक संज्ञा",
    emoji: "🔤",
    definition: "A gerund is a verb form ending in -ing that works as a NOUN in a sentence.",
    definitionHindi: "Gerund क्रिया का वह रूप है जो -ing लगाकर संज्ञा (Noun) का काम करता है।",
    color: "bg-fuchsia-500 dark:bg-fuchsia-600",
    borderColor: "border-fuchsia-500",
    textColor: "text-fuchsia-700 dark:text-fuchsia-300",
    types: [
      {
        name: "Gerund as Subject",
        nameHindi: "कर्ता के रूप में",
        description: "The gerund acts as the subject of the sentence.",
        descriptionHindi: "Gerund वाक्य में कर्ता (Subject) का काम करता है।",
        examples: "Swimming is fun. Reading helps the mind. Walking is good for health.",
      },
      {
        name: "Gerund as Object",
        nameHindi: "कर्म के रूप में",
        description: "The gerund acts as the object of a verb.",
        descriptionHindi: "Gerund क्रिया के कर्म (Object) का काम करता है।",
        examples: "I enjoy reading. She likes dancing. He stopped smoking.",
      },
      {
        name: "Gerund after Preposition",
        nameHindi: "Preposition के बाद",
        description: "A gerund is used after prepositions (of, in, at, for, about, etc.).",
        descriptionHindi: "Preposition के बाद हमेशा Gerund (-ing) आता है।",
        examples: "He is fond of reading. She is good at singing. I am tired of waiting.",
      },
      {
        name: "Gerund as Complement",
        nameHindi: "पूरक के रूप में",
        description: "The gerund completes the meaning after 'is/was/are'.",
        descriptionHindi: "is/was/are के बाद Gerund अर्थ पूरा करता है।",
        examples: "My hobby is painting. His job is teaching. The best exercise is walking.",
      },
    ],
  },
  {
    id: "infinitive",
    name: "Infinitive",
    nameHindi: "क्रियार्थक संज्ञा",
    emoji: "🎯",
    definition: "An infinitive is the base form of a verb with 'to' — to eat, to play, to read. It can work as a noun, adjective, or adverb.",
    definitionHindi: "Infinitive क्रिया का मूल रूप है जिसके पहले 'to' लगता है — to eat, to play। यह Noun, Adjective, Adverb का काम कर सकता है।",
    color: "bg-emerald-600 dark:bg-emerald-700",
    borderColor: "border-emerald-600",
    textColor: "text-emerald-800 dark:text-emerald-300",
    types: [
      {
        name: "Infinitive as Noun",
        nameHindi: "Noun के रूप में",
        description: "The infinitive works as a noun (subject or object).",
        descriptionHindi: "Infinitive संज्ञा का काम करता है (कर्ता या कर्म)।",
        examples: "To err is human. I want to eat. She loves to dance.",
      },
      {
        name: "Infinitive as Adjective",
        nameHindi: "Adjective के रूप में",
        description: "The infinitive describes a noun (tells 'which one').",
        descriptionHindi: "Infinitive संज्ञा की विशेषता बताता है।",
        examples: "Give me a book to read. I need water to drink. She has work to do.",
      },
      {
        name: "Infinitive as Adverb",
        nameHindi: "Adverb के रूप में",
        description: "The infinitive tells 'why' — purpose of the action.",
        descriptionHindi: "Infinitive बताता है 'क्यों' — क्रिया का उद्देश्य।",
        examples: "He came to help. She studies to pass. I eat to live.",
      },
      {
        name: "Bare Infinitive (without 'to')",
        nameHindi: "बिना 'to' वाला Infinitive",
        description: "After modals (can, may, must, should) and let/make/help, 'to' is dropped.",
        descriptionHindi: "Modals (can, may, must) और let/make/help के बाद 'to' नहीं लगता।",
        examples: "She can sing. Let him go. I must study. Help me carry this.",
      },
    ],
  },
  {
    id: "participle",
    name: "Participle",
    nameHindi: "कृदंत / विशेषणात्मक क्रिया",
    emoji: "✨",
    definition: "A participle is a verb form that works as an ADJECTIVE. It describes a noun.",
    definitionHindi: "Participle क्रिया का वह रूप है जो विशेषण (Adjective) का काम करता है — संज्ञा की विशेषता बताता है।",
    color: "bg-yellow-500 dark:bg-yellow-600",
    borderColor: "border-yellow-500",
    textColor: "text-yellow-700 dark:text-yellow-300",
    types: [
      {
        name: "Present Participle (V-ing)",
        nameHindi: "वर्तमान कृदंत",
        description: "Verb + ing used as adjective. Shows ongoing action.",
        descriptionHindi: "क्रिया + ing विशेषण का काम करता है। जारी काम बताता है।",
        examples: "a running boy, the crying baby, boiling water, a smiling girl",
      },
      {
        name: "Past Participle (V3)",
        nameHindi: "भूतकालिक कृदंत",
        description: "Verb's 3rd form (V3) used as adjective. Shows completed action.",
        descriptionHindi: "क्रिया का तीसरा रूप (V3) विशेषण का काम करता है। पूरा हुआ काम।",
        examples: "a broken window, the stolen car, baked bread, a tired man",
      },
      {
        name: "Perfect Participle",
        nameHindi: "पूर्ण कृदंत",
        description: "Having + V3. Shows one action completed before another.",
        descriptionHindi: "Having + V3। एक काम दूसरे से पहले पूरा होना बताता है।",
        examples: "Having finished the work, he left. Having eaten lunch, she slept.",
      },
    ],
  },
  {
    id: "clause",
    name: "Clause",
    nameHindi: "उपवाक्य",
    emoji: "🧩",
    definition: "A clause is a group of words that has a subject and a verb. It may or may not make complete sense alone.",
    definitionHindi: "उपवाक्य शब्दों का समूह है जिसमें कर्ता और क्रिया होती है। यह अकेला पूरा अर्थ दे भी सकता है और नहीं भी।",
    color: "bg-stone-500 dark:bg-stone-600",
    borderColor: "border-stone-500",
    textColor: "text-stone-700 dark:text-stone-300",
    types: [
      {
        name: "Independent (Main) Clause",
        nameHindi: "मुख्य उपवाक्य",
        description: "Makes complete sense on its own. Can stand as a sentence.",
        descriptionHindi: "अकेले पूरा अर्थ देता है। खुद एक वाक्य बन सकता है।",
        examples: "I like mangoes. She went home. The dog barked loudly.",
      },
      {
        name: "Dependent (Subordinate) Clause",
        nameHindi: "आश्रित उपवाक्य",
        description: "Cannot stand alone. Depends on the main clause for meaning.",
        descriptionHindi: "अकेला पूरा अर्थ नहीं देता। मुख्य उपवाक्य पर निर्भर है।",
        examples: "because I was hungry, when she came, if it rains, although he tried",
      },
      {
        name: "Noun Clause",
        nameHindi: "संज्ञा उपवाक्य",
        description: "A dependent clause that works as a noun (subject/object).",
        descriptionHindi: "आश्रित उपवाक्य जो संज्ञा का काम करता है।",
        examples: "I know that he is honest. What she said is true. Tell me where you live.",
      },
      {
        name: "Adjective (Relative) Clause",
        nameHindi: "विशेषण उपवाक्य",
        description: "A dependent clause that describes a noun. Uses who/which/that/where.",
        descriptionHindi: "आश्रित उपवाक्य जो संज्ञा की विशेषता बताता है।",
        examples: "The boy who won is my friend. The book that I read was good.",
      },
      {
        name: "Adverb Clause",
        nameHindi: "क्रिया विशेषण उपवाक्य",
        description: "A dependent clause that works as an adverb (tells when, where, why, how).",
        descriptionHindi: "आश्रित उपवाक्य जो क्रिया की विशेषता बताता है — कब, कहाँ, क्यों, कैसे।",
        examples: "I will go if it stops raining. She cried because she was sad.",
      },
    ],
  },
  {
    id: "punctuation",
    name: "Punctuation",
    nameHindi: "विराम चिह्न",
    emoji: "✏️",
    definition: "Punctuation marks are symbols used in writing to separate sentences, show pauses, and clarify meaning.",
    definitionHindi: "विराम चिह्न लिखते समय प्रयोग होने वाले चिह्न हैं जो वाक्यों को अलग करते हैं और अर्थ स्पष्ट करते हैं।",
    color: "bg-gray-500 dark:bg-gray-600",
    borderColor: "border-gray-500",
    textColor: "text-gray-700 dark:text-gray-300",
    types: [
      {
        name: "Full Stop / Period (.)",
        nameHindi: "पूर्ण विराम",
        description: "Used at the end of a statement or declarative sentence.",
        descriptionHindi: "कथनात्मक वाक्य के अंत में लगता है।",
        examples: "I am a student. She likes tea. India is a great country.",
      },
      {
        name: "Comma (,)",
        nameHindi: "अल्प विराम",
        description: "Shows a short pause. Used in lists, after introductions, and before conjunctions.",
        descriptionHindi: "छोटा ठहराव। सूची में, शुरुआती शब्दों के बाद, conjunctions से पहले।",
        examples: "I bought apples, bananas, and grapes. Yes, I will come.",
      },
      {
        name: "Question Mark (?)",
        nameHindi: "प्रश्नवाचक चिह्न",
        description: "Used at the end of a question.",
        descriptionHindi: "प्रश्नवाचक वाक्य के अंत में लगता है।",
        examples: "What is your name? Are you ready? Where do you live?",
      },
      {
        name: "Exclamation Mark (!)",
        nameHindi: "विस्मयादिबोधक चिह्न",
        description: "Shows strong emotion — joy, surprise, anger, or commands.",
        descriptionHindi: "तीव्र भावना — खुशी, आश्चर्य, गुस्सा, या आदेश।",
        examples: "Wow! What a beautiful view! Stop! Help me!",
      },
      {
        name: "Apostrophe (')",
        nameHindi: "ऊर्ध्व विराम",
        description: "Shows possession (Ram's) or contraction (don't = do not).",
        descriptionHindi: "अधिकार (Ram's) या शब्दों का छोटा रूप (don't) बताता है।",
        examples: "Ram's book. It's raining. She doesn't know. The children's toys.",
      },
      {
        name: "Inverted Commas / Quotation Marks (\" \")",
        nameHindi: "उद्धरण चिह्न",
        description: "Used for direct speech and to quote exact words.",
        descriptionHindi: "Direct Speech और किसी के exact शब्द लिखने के लिए।",
        examples: "He said, \"I am fine.\" \"Help!\" she cried. The sign said \"No Entry\".",
      },
    ],
  },
];
